### ISSUE TITLE
Allow project.dependencies to be interpreted as conda-forge dependencies

### ISSUE THREAD

**Issue by maresb** [prefix-dev/pixi#1646] opened 2024-07-22 07:52 UTC
# Duplicate of #532

### Problem description

[Original Discord discussion](https://discord.com/channels/1082332781146800168/1264299390336634880)

~Currently pixi interprets `project.dependencies` as `tool.pixi.pypi-dependencies`. (At least I think so, but I'm not sure of the details. Does it also read from `project.dependencies` when using `pixi.toml`?) In order to install these dependencies instead with conda, they currently need to be duplicated to `tool.pixi.dependencies`.~

~My request is to add `pixi.toml` settings that accomplish the following:~

~1. Have a setting so that everything in `project.dependencies` is by default interpreted as a conda-forge dependency instead of a PyPI dependency~
~2. Be able to make an exception for individual packages, i.e. everything under `project.dependencies` should be a conda-forge dependency except for `my-special-package-1` and `my-special-package-2`.~
~3. Be able to override the default pypi→conda-forge mapping in case it's wrong~

~Advanced considerations:~

~* Some people will want to use channels other than conda-forge (and pip repositories other than PyPI), and these might require authentication~
~* How to deal with multiple features/environments~

**Comment by olivier-lacroix** [comment] 2024-07-22 08:04
I believe this is a duplicate of https://github.com/prefix-dev/pixi/issues/532

It’s something I want as well. I will implement it (but no promise on the timeline :-)

**Comment by tdejager** [comment] 2024-07-22 08:12
@olivier-lacroix @maresb made it on my recommendenation. Forgot about the other issue, sorry about that! Should I merge this note at the end of that issues, as I think it has some good points laid out?

**Comment by maresb** [comment] 2024-07-22 08:13
I'll migrate this to a comment on that other issue...

**Closed** 2024-07-22 08:16 UTC
Labels: enhancement

**Comment by tdejager** [comment] 2024-07-22 08:22
Thanks @maresb, sorry about that!
