### ISSUE TITLE
Let `pixi add` pin major versions instead of minor versions

### ISSUE THREAD

**Issue by Hofer-Julian** [prefix-dev/pixi#1562] opened 2024-07-04 07:00 UTC
### Problem description

Running `pixi add python` on an empty pixi project currently gives this:
```toml
[dependencies]
python = ">=3.12.4,<3.13"
```

I am arguing the expected version range should be this:
```toml
[dependencies]
python = ">=3.12.4,<4"
```

This is also the behavior `cargo add` has.

For major version zero, the situation is a bit more complicated. According to SemVer there are no [stability guarantees](https://semver.org/#spec-item-4) at all:
> Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.

Rust and Julia define that different, but to my knowledge, most ecosystems don't overrule that specification.
For major zero, I think people will have to choose the [pinning strategy](https://github.com/prefix-dev/pixi/pull/1516) themselves.
Pinning the major versions instead of the minor versions still makes sense in my opinion.

**Comment by baszalmstra** [comment] 2024-07-04 08:27
Although I agree with you in theory, in practice breaking changes still occur quite frequently for minor bumps, especially in the python world. Thats why we initially settled on pinning the minor version instead of the major. 

That being said, I would not be opposed to this change. 👍

**Comment by pavelzw** [comment] 2024-07-04 09:25
Isn't this a duplicate of #639?

**Comment by Hofer-Julian** [comment] 2024-07-04 09:29
> Isn't this a duplicate of #639?

I think it's a good idea to link it here. But considering that it started with a completely different proposal (removing upper bounds all together) I would prefer to close #639 and keep this one.

**Comment by pavelzw** [comment] 2024-07-04 09:31
as stated in https://github.com/prefix-dev/pixi/issues/639#issuecomment-1976749841, i would prefer semver over major versions

**Comment by Hofer-Julian** [comment] 2024-07-04 09:46
> as stated in [#639 (comment)](https://github.com/prefix-dev/pixi/issues/639#issuecomment-1976749841), i would prefer semver over major versions

As mentioned in the issue description, that is only guaranteed to work (to my knowledge) with Rust and Julia.
According to SemVer zero leading versions can break anytime, including patch releases.

**Comment by Hofer-Julian** [comment] 2024-07-04 09:47
The only thing we can do is to always zero-leading versions, but I don't think that anyone will be happy with that.

**Comment by pavelzw** [comment] 2024-07-04 10:09
oh i didn't read this 😅 i'm wondering how many people actually follow this 🤔
at least i'm always bumping the minor part for breaking changes in pre-v1

**Comment by Hofer-Julian** [comment] 2024-07-04 12:29
> We could do the same behavior as cargo right? Pin the first (left most) non-zero? So for 3.12.4 it would be <4, but for 0.1.1 it would be <0.2?

Yes, I think that's also the behavior @pavelzw would like. I am not opposed to that.

I am just pointing out that semantic versioning works a bit different for Cargo than it does for "vanilla" SemVer. 

Not only 0.1.0 -> 0.2.0 is allowed to break, but also 0.1.0 -> 0.1.1

**Comment by pavelzw** [comment] 2024-07-04 12:29
i would prefer that and call it something like `semver` (even though it's not strictly semver). as long as we properly document what it's doing, i think this is okay

**Comment by Hofer-Julian** [comment] 2024-07-04 12:32
> i would prefer that and call it something like `semver` (even though it's not strictly semver). as long as we properly document what it's doing, i think this is okay

`cargo-semver` :P

(I don't really know if the Cargo people were the first ones actually writing it down)

**Comment by baszalmstra** [comment] 2024-07-04 12:34
The npm caret operator (^) also does this I think: https://docs.npmjs.com/cli/v6/using-npm/semver#caret-ranges-123-025-004

**Comment by maurosilber** [comment] 2024-07-12 13:49
I would prefer if the default is no upper bound, as discussed here: https://iscinumpy.dev/post/bound-version-constraints/

Pinning dependencies is more useful for applications than libraries, and for that we would have `pixi.lock`, woudn't we?

**Comment by baszalmstra** [comment] 2024-07-12 14:18
https://github.com/prefix-dev/pixi/pull/1516 lets you configure the default. But if no configuration is specified I think we should default to "semver" as proposed in this issue (and implemented in the mentioned PR).

**Closed** 2024-07-19 13:11 UTC
Labels: enhancement
