### ISSUE TITLE
Misleading error in case of duplicated dependency in pyproject.toml

### ISSUE THREAD

**Issue by traversaro** [prefix-dev/pixi#1268] opened 2024-04-24 14:56 UTC
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
git clone https://gist.github.com/traversaro/5a3ce5afe0eb4eb7e5474582273fa624 piximwe
cd piximwe
pixi run start
```

this results in the error:
~~~
traversaro@IITBMP014LW012:~/piximwe$ pixi run start
  × could not find pixi.toml or pyproject.toml which is configured to use pixi
~~~

however, `pyproject.toml` is configured to use pixi, simply there is the error in the metadata (in particular there is a duplicated dependency). If instead one does `pixi init .`, there is a much more descriptive error:

~~~
traversaro@IITBMP014LW012:~/piximwe$ pixi init .
  × failed to parse project manifest
    ╭─[pyproject.toml:14:1]
 13 │ numpy = "*"
 14 │ numpy = "*"
    · ┬
    · ╰── duplicate key `numpy` in table `tool.pixi.dependencies`
 15 │
    ╰────
~~~

### Issue description

See reproducible example.

### Expected behavior

It would be great to have a more descriptive error if a dependency is duplicated.

**Comment by traversaro** [comment] 2024-04-24 14:57
Problem found by @flferretti

**Comment by traversaro** [comment] 2024-04-24 15:00
The problem is not present if `pixi.toml` is used, for example with:
~~~
[project]
name = "piximws"
version = "0.1.0"
description = "Add a short description here"
authors = ["Silvio Traversaro <silvio@traversaro.it>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]
start = "echo"

[dependencies]
numpy = "*"
numpy = "*"
~~~

pixi run start results in a clear error:
~~~
traversaro@IITBMP014LW012:~/piximws$ pixi run start
  × failed to parse project manifest
    ╭─[pixi.toml:14:1]
 13 │ numpy = "*"
 14 │ numpy = "*"
    · ┬
    · ╰── duplicate key `numpy` in table `dependencies`
    ╰────
~~~

**Comment by tdejager** [comment] 2024-04-25 08:08
Yes, this seems like this could use an improvement for sure!

**Comment by ruben-arts** [comment] 2024-04-25 20:37
That is an interesting one.

This is a toml error, so would you expect pixi to always report toml errors of pyproject.toml? Even if it is not used as a pixi manifest?

E.g. this will give you the same result:
```toml
[project]
name = "my_project"
requires-python = ">=3.9" # <<<
requires-python = ">=3.9" # <<<
dependencies = [
    "numpy",
]

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "osx-64", "win-64"]
```

As in, it will not be read as a valid toml file so pixi skips it as a viable option currently.

**Comment by baszalmstra** [comment] 2024-08-22 15:00
Duplicate of https://github.com/prefix-dev/pixi/issues/1777

**Closed by baszalmstra** 2024-08-22 15:00 UTC
Labels: bug
