### ISSUE TITLE
Pixi editable pypi packages aren't visible to VSCode Pylance

### ISSUE THREAD

**Issue by kcajf** [prefix-dev/pixi#1633] opened 2024-07-18 17:20 UTC
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

install a pixi editable module, set the python interpreter in VSCode to the pixi interpreter, and try to import the editable module. VSCode won't be able to find it (i.e. go-to-definition won't work).

### Issue description

https://github.com/microsoft/pylance-release/issues/3473

I think this issue explains the problem. It doesn't look like pixi installs editable dependencies in a way that pylance (and it seems like a few other tools) understands.

### Expected behavior

Pip has a config setting for this. Not sure if something similar would be suitable for pixi?

**Comment by olivier-lacroix** [comment] 2024-07-29 03:11
@tdejager this may be a good reason to switch the default build backend to hatchling? what do you think?

**Comment by olivier-lacroix** [comment] 2024-08-02 04:41
Looks like hatch is not enough. See https://github.com/microsoft/pylance-release/issues/6218

**Comment by Hofer-Julian** [comment] 2024-08-05 06:04
> Looks like hatch is not enough. See [microsoft/pylance-release#6218](https://github.com/microsoft/pylance-release/issues/6218)

This pylance issue is closed now, does this mean we can close this one as well?

**Comment by olivier-lacroix** [comment] 2024-08-05 08:12
It seems to be a bit hit and miss. It works for some people in our team, and for some days… making it hard to understand what is happening.

**Comment by ruben-arts** [comment] 2024-08-05 12:51
Closing for now, reopen if we've got a more concrete reproducible situation.

**Closed by ruben-arts** 2024-08-05 12:51 UTC
Labels: bug

**Comment by kcajf** [comment] 2024-09-30 10:15
This is still a problem for me.

**Comment by oliver-batchelor** [comment] 2025-01-27 08:11
I'm just getting into pixi now and having the same problem, I used to have to install my ediable packages with "editable_mode=compat" to make this work.

I have the pixi environment selected, all seems well but the local packages aren't recognised like before?
