### ISSUE TITLE
custom pypi index

### ISSUE THREAD

**Issue by zen-xu** [prefix-dev/pixi#1094] opened 2024-04-01 08:13 UTC
### Problem description

I use self-hosted pypi within the company, and `uv` can set the pypi index through environment variables.

```bash
export UV_INDEX_URL=xxxx
export UV_EXTRA_INDEX_URL=xxxx
```

Since pixi uses uv to install pip-related packages, I hope this can be supported.

**Comment by olivier-lacroix** [comment] 2024-04-01 08:36
We would need create that struct to pass it to uv

pub struct IndexLocations {
    index: Option<IndexUrl>,
    extra_index: Vec<IndexUrl>,
    flat_index: Vec<FlatIndexLocation>,
    no_index: bool,
}

@tdejager , what would be your preference in terms of TOML configuration? a `pypi-index-location` table?

**Comment by zen-xu** [comment] 2024-04-01 09:03
I think `pypi-options` would be more suitable.

**Comment by gzm55** [comment] 2024-04-01 12:43
does this related with #906?

**Comment by baszalmstra** [comment] 2024-04-02 07:49
Also related: https://github.com/prefix-dev/pixi/issues/588

**Comment by vigneshmanick** [comment] 2024-04-07 08:09
also related to #1058

**Comment by tdejager** [comment] 2024-04-08 11:26
@olivier-lacroix @gzm55 @zen-xu @vigneshmanick  Would it be fine to have this on the level of project similar to channels?

**Comment by vigneshmanick** [comment] 2024-04-08 11:48
I am fine with the project level definition, but it would also be good if it can be defined **per** package similar to how the conda dependencies are mentioned in the current [documentation ](https://pixi.sh/latest/configuration/#dependencies). 

```toml
[dependencies]
vtk-osmesa = { version = "~=9.3", channel = "conda-forge" }
```

similar way for pypi should be

```toml
[pypi-dependencies]
vtk-osmesa = { version = "~=9.3", extra-index-url= "wheels.vtk.org" }
```

**Comment by gzm55** [comment] 2024-04-08 11:50
> @olivier-lacroix @gzm55 @zen-xu @vigneshmanick Would it be fine to have this on the level of project similar to channels?

LGTM. both index-url and extra index-urls need to be set separately.

**Comment by tdejager** [comment] 2024-04-08 12:52
> I am fine with the project level definition, but it would also be good if it can be defined **per** package similar to how the conda dependencies are mentioned in the current [documentation ](https://pixi.sh/latest/configuration/#dependencies).
> 
> ```toml
> [dependencies]
> vtk-osmesa = { version = "~=9.3", channel = "conda-forge" }
> ```
> 
> similar way for pypi should be
> 
> ```toml
> [pypi-dependencies]
> vtk-osmesa = { version = "~=9.3", extra-index-url= "wheels.vtk.org" }
> ```

That would be awesome I agree, I'm afraid that's technically more difficult because `uv` does not support such fine-grained selection (yet). We could do it on a feature level, like only use an extra-index-url for a specific feature.

**Comment by olivier-lacroix** [comment] 2024-04-09 00:00
@tdejager project/ feature level settings mirroring the UV struct would be sufficient yes.

**Comment by zachcp** [comment] 2024-04-09 19:14
Thank you @tdejager . Looking forward to this.   ( its the primary blocker for uptake in my company. )

**Comment by tdejager** [comment] 2024-04-11 08:15
I'm now just thinking, all of these optional

```toml
[project]
...
[pypi-options]
# When not used, will use uv default which is just pypi
primary-index = "pypi.org/simple"
extra-indices = ["foo", "bar"]
flat-indices = ["path/to/index"]
```
@ruben-arts and others in-thread WDYT?

**Comment by vigneshmanick** [comment] 2024-04-11 09:07
this looks good and should cover my usecase

**Comment by ruben-arts** [comment] 2024-04-11 09:08
That should be fine! It should be part of the `feature` table so you can define it per feature right?

**Comment by tdejager** [comment] 2024-04-11 10:29
@ruben-arts Ideally yes, how does this work for channels now because part of it also at a project level, but you can redefine per feature? Also the `primary-index` should overwrite, because it can only have one value.

**Comment by ruben-arts** [comment] 2024-04-11 10:46
The platforms and channels are special cases where they are part of the `feature` definition and the `project`. 

Should we just use `index` for the `primary-index`? Also what is the difference in code path between the `index` and `extra_index` in `uv`?

**Comment by tdejager** [comment] 2024-04-11 11:54
1. If you have no `primary-index` but only extra indices it will use `pypi.org/simple` and the extra ones.
2. If you only have a `primary-index` it will use only that.

I'm fine with naming it `index` I thought naming it `primary-index` would avoid the confusion about the above statements. But it seems this is not the case :D

**Comment by tdejager** [comment] 2024-04-18 14:18
Started on this: https://github.com/prefix-dev/pixi/pull/1225

**Comment by gzm55** [comment] 2024-04-25 22:37
> Started on this: #1225

@tdejager can we set the pypi index urls in global configuration? or fallback to pip.conf?

**Comment by zachcp** [comment] 2024-04-30 15:54
...( excitedly waits for the release ).....

**Comment by tdejager** [comment] 2024-05-07 09:03
> > Started on this: #1225
> 
> @tdejager can we also set the pypi index urls in global configuration? or fallback to pip.conf?

In the current version you can set them in the global config, they will be automatically added on init. But they are still required in the manifest file. This was chosen because otherwise the installs are not reproducible across systems.

**Comment by tdejager** [comment] 2024-05-07 09:05
This feature should now be included in the latest release (with some basic ways of authenticating, through uv's keyring or netrc features).

See documentation: https://pixi.sh/latest/reference/configuration/#the-pypi-options-table

I will be closing this issue for now, feel free to make a new issue if there are any problems.

**Closed by tdejager** 2024-05-07 09:05 UTC
Labels: enhancement, pypi, uv

**Comment by dboeckenhoff** [comment] 2025-01-29 12:15
Now (29.01.2025) it is under https://pixi.sh/latest/reference/pixi_manifest/#the-pypi-options-table
