### ISSUE TITLE
Support bash activate/deactivate scripts

### ISSUE THREAD

**Issue by dhirschfeld** [prefix-dev/pixi#597] opened 2023-12-26 09:29 UTC
### Problem description

Some activate/deactivate scripts are written with bash-specific syntax (e.g. `dotnet`). These currently break when installed into a `pixi` environment.

**Comment by dhirschfeld** [comment] 2023-12-26 09:31
I think `conda` has long recommended to only use `sh` syntax so it could be viewed as a bug with the scripts however they do still work with `conda`/`mamba`

**Comment by dhirschfeld** [comment] 2023-12-26 09:33
The specific example would be (better) solved by a declarative way to set environment variables and paths but if you want to support the current ecosystem of `conda` packages there are probably other examples of `bash`-specific activation scripts out there.

**Comment by baszalmstra** [comment] 2024-01-02 08:10
Can you share the exact issue that you run in to? Does pixi not run the activation scripts at all? Or does it error on invalid syntax? As far as Im aware we also simply run `bash` to determine the activation environment.

There is a little known feature that `pixi` supports (as well as `conda`/`mamba`), packages can install a json file in `$PREFIX/etc/conda/env_vars.d/<mypkg>.json` that contains a dictionary of environment variables. These are automatically injected uponactivating the env.

Im pretty sure @wolfv wants to integrate this into the new recipe format thats introduced with `rattler-build`.

**Comment by dhirschfeld** [comment] 2024-01-02 09:54
The errors I was seeing:
```
~/.pixi/bin/git-credential-manager: 1: ~/.pixi/envs/git-credential-manager/etc/conda/activate.d/dotnet-root.sh: function: not found
~/.pixi/bin/git-credential-manager: 3: ~/.pixi/envs/git-credential-manager/etc/conda/activate.d/dotnet-root.sh: [[: not found
~/.pixi/bin/git-credential-manager: 6: local: not in a function
```
From https://github.com/conda-forge/dotnet-feedstock/blob/main/recipe/activate.d/dotnet-root.sh

**Comment by dhirschfeld** [comment] 2024-01-02 09:57
> There is a little known feature that `pixi` supports (as well as `conda`/`mamba`), packages can install a json file

I've come across that before and think it's a great improvement, at least for env vars (I'd like the same for path entries too!). I haven't used it though as last I checked the implementation was buggy. Maybe that's changed (or been fixed in pixi)?

**Comment by baszalmstra** [comment] 2024-08-22 13:32
I cannot reproduce this on linux. Closing for now. Feel free to reopen if the issue persists.

```shell
pixi init dotnet
cd dotnet
pixi add dotnet
pixi run 'echo $DOTNET_CLI_TELEMETRY_OPTOUT'
# Should print `true` as set by the activation script
```

**Closed by baszalmstra** 2024-08-22 13:32 UTC
Labels: enhancement

**Comment by dhirschfeld** [comment] 2024-08-22 13:54
Cool, thanks - will give it a go again...

**Comment by aswordok** [comment] 2025-09-29 08:24
> Can you share the exact issue that you run in to? Does pixi not run the activation scripts at all? Or does it error on invalid syntax? As far as Im aware we also simply run `bash` to determine the activation environment.你能分享一下你遇到的具体问题吗？是 pixi 完全不会运行激活脚本，还是它在无效语法上出错？据我所知，我们也通过运行 `bash` 来确定激活环境。
> 
> There is a little known feature that `pixi` supports (as well as `conda`/`mamba`), packages can install a json file in `$PREFIX/etc/conda/env_vars.d/<mypkg>.json` that contains a dictionary of environment variables. These are automatically injected uponactivating the env.有一个鲜为人知的特性， `pixi` 支持（以及 `conda` / `mamba` 也支持），软件包可以在 `$PREFIX/etc/conda/env_vars.d/<mypkg>.json` 中安装一个包含环境变量字典的 json 文件。在激活环境时，这些变量会自动注入。
> 
> Im pretty sure [@wolfv](https://github.com/wolfv) wants to integrate this into the new recipe format thats introduced with `rattler-build`.我确信希望将这个特性集成到 `rattler-build` 引入的新配方格式中。

Solved my problem.
I have multiple environments and need to switch between them freely, so I manually created a JSON file.
type "D:\+AI\313\.pixi\envs\default\etc\conda\env_vars.d\env.json"
{
  "CUDA_PATH_V13_0": "C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v13.0",
  "CUDA_HOME": "C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v13.0",
  "CUDA_PATH": "C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v13.0",
  "Path": "%CUDA_PATH_V13_0%\\bin;%CUDA_PATH_V13_0%\\bin\\x64;%Path%"
}
By using "gci env:" for verification, it seems that the injection was successful.
windows11 + Powershell
