### ISSUE TITLE
Add `pixi tree` and `pixi tree -i` command

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/pixi#238] opened 2023-07-29 21:26 UTC
It would be nice to have `pixi tree` and `pixi tree -i` similar to `cargo tree` and `cargo tree -i`

<details>
<summary>old resolved issue for `pixi list`</summary>

It would be nice to have a command that lists all installed packages.

```
$ pixi install
$ pixi list
python   <build-string> <version>
...
$ pixi list --all-platforms
<same thing but all platforms>
$ pixi list --json
...
```

Maybe we could also highlight the explicitly specified dependencies similar to micromamba
![image](https://github.com/prefix-dev/pixi/assets/29506042/6fab6191-6f75-47f4-ae0b-fcbedf810f3d)

</details>

**Comment by baszalmstra** [comment] 2023-08-14 07:47
I think we should definitely add this. Poetry uses the `show` command instead of `list` I think.

`cargo` has the `tree` command which also enables showing the dependency graph as a tree (and in reverse). Maybe that might also be useful?

**Comment by pavelzw** [comment] 2023-08-14 07:51
Yes, tree (+ reverse) would also be awesome!

**Comment by traversaro** [comment] 2023-09-09 10:55
Another place were this is useful: in RoboStack template we ask users reporting an issue to report the output of `conda list`/`mamba list`/`micromamba list` for reproducibility. At the moment, pixi users do not have an equivalent command, so it is not clear what we should recommend them, see https://github.com/RoboStack/ros-humble/issues/100 . In theory `pixi.lock` contains that info in some form, but it is much less readable.

**Comment by gagandeepp** [comment] 2023-10-23 11:27
Interested please assign

**Comment by ruben-arts** [comment] 2023-12-22 14:12
Nope @raceychan, go ahead if you like!

**Comment by ruben-arts** [comment] 2024-01-26 10:39
`pixi list` is merged. But we're still missing the `pixi tree` which would also be a nice feature. Best example I know would be `cargo tree`.

**Comment by pavelzw** [comment] 2024-01-26 10:50
And `cargo tree -i` 😉

**Comment by abkfenris** [comment] 2024-03-26 23:22
I took a swing at implementing them in my branch here: https://github.com/abkfenris/pixi/compare/manifest-env-var...abkfenris:pixi:tree

```sh
pixi on  tree is 📦 v0.17.1 via 🦀 v1.76.0
❯
pixi tree pre-commit
└── pre-commit v3.3.3
    ├── cfgv v3.3.1
    │   └── python v3.12.2
    │       ├── bzip2 v1.0.8
    │       ├── libexpat v2.6.2
    │       ├── libffi v3.4.2
    │       ├── libsqlite v3.45.2
    │       │   └── libzlib v1.2.13
    │       ├── libzlib v1.2.13 (*)
    │       ├── ncurses v6.4.20240210
    │       ├── openssl v3.2.1
    │       ├── readline v8.2
    │       │   └── ncurses v6.4.20240210 (*)
    │       ├── tk v8.6.13
    │       │   └── libzlib v1.2.13 (*)
    │       └── xz v5.2.6
    ├── identify v2.5.35
    │   └── python v3.12.2 (*)
    ├── nodeenv v1.8.0
    │   └── python v3.12.2 (*)
    ├── python v3.12.2 (*)
    ├── pyyaml v6.0.1
    │   ├── python v3.12.2 (*)
    │   ├── python v3.12.2 (*)
    │   ├── python_abi v3.12
    │   └── yaml v0.2.5
    └── virtualenv v20.25.1
        ├── distlib v0.3.8
        │   └── python v3.12.2 (*)
        ├── filelock v3.13.1
        │   └── python v3.12.2 (*)
        ├── platformdirs v4.2.0
        │   └── python v3.12.2 (*)
        └── python v3.12.2 (*)
```

```sh
pixi on  tree is 📦 v0.17.1 via 🦀 v1.76.0
❯
pixi tree -i yaml

yaml
└── pyyaml
    └── pre-commit

ruamel.yaml
├── cffconvert
└── pykwalify
    └── cffconvert

pyyaml
└── pre-commit

ruamel.yaml.clib
└── ruamel.yaml
    ├── cffconvert
    └── pykwalify
        └── cffconvert
```

It's not quite ready for a PR yet as I haven't implemented visiting or versions for the inverted tree, and I built it off of another branch I already have a PR in progress for.

**Comment by pavelzw** [comment] 2024-03-26 23:36
Looks great!
What does it look like when running `pixi tree` (without pre-commit)? All dependencies are shown then?

**Comment by abkfenris** [comment] 2024-03-27 00:22
Yup, it'll print out everything if it's not given a regex pattern.

<details>

```sh
pixi tree
├── pre-commit v3.3.3
│   ├── cfgv v3.3.1
│   │   └── python v3.12.2
│   │       ├── bzip2 v1.0.8
│   │       ├── libexpat v2.6.2
│   │       ├── libffi v3.4.2
│   │       ├── libsqlite v3.45.2
│   │       │   └── libzlib v1.2.13
│   │       ├── libzlib v1.2.13 (*)
│   │       ├── ncurses v6.4.20240210
│   │       ├── openssl v3.2.1
│   │       ├── readline v8.2
│   │       │   └── ncurses v6.4.20240210 (*)
│   │       ├── tk v8.6.13
│   │       │   └── libzlib v1.2.13 (*)
│   │       └── xz v5.2.6
│   ├── identify v2.5.35
│   │   └── python v3.12.2 (*)
│   ├── nodeenv v1.8.0
│   │   └── python v3.12.2 (*)
│   ├── python v3.12.2 (*)
│   ├── pyyaml v6.0.1
│   │   ├── python v3.12.2 (*)
│   │   ├── python v3.12.2 (*)
│   │   ├── python_abi v3.12
│   │   └── yaml v0.2.5
│   └── virtualenv v20.25.1
│       ├── distlib v0.3.8
│       │   └── python v3.12.2 (*)
│       ├── filelock v3.13.1
│       │   └── python v3.12.2 (*)
│       ├── platformdirs v4.2.0
│       │   └── python v3.12.2 (*)
│       └── python v3.12.2 (*)
├── rust v1.76.0
│   └── rust-std-aarch64-apple-darwin v1.76.0
├── openssl v3.2.1
├── pkg-config v0.29.2
│   ├── libglib v2.78.4
│   │   ├── gettext v0.21.1
│   │   │   └── libiconv v1.17
│   │   ├── libcxx v16.0.6
│   │   ├── libffi v3.4.2 (*)
│   │   ├── libiconv v1.17 (*)
│   │   ├── libzlib v1.2.13 (*)
│   │   └── pcre2 v10.42
│   │       ├── bzip2 v1.0.8 (*)
│   │       └── libzlib v1.2.13 (*)
│   └── libiconv v1.17 (*)
├── git v2.42.0
│   ├── libexpat v2.6.2 (*)
│   ├── libiconv v1.17 (*)
│   ├── libzlib v1.2.13 (*)
│   ├── openssl v3.2.1 (*)
│   ├── pcre2 v10.42 (*)
│   └── perl v5.32.1
├── cffconvert v2.0.0
│   ├── click v8.1.7
│   │   └── python v3.12.2 (*)
│   ├── jsonschema v3.2.0
│   │   ├── attrs v23.2.0
│   │   │   └── python v3.12.2 (*)
│   │   ├── pyrsistent v0.20.0
│   │   │   ├── python v3.12.2 (*)
│   │   │   ├── python v3.12.2 (*)
│   │   │   └── python_abi v3.12 (*)
│   │   ├── python v3.12.2 (*)
│   │   └── six v1.16.0
│   ├── pykwalify v1.8.0
│   │   ├── docopt v0.6.2
│   │   ├── python v3.12.2 (*)
│   │   ├── python-dateutil v2.9.0
│   │   │   ├── python v3.12.2 (*)
│   │   │   └── six v1.16.0 (*)
│   │   └── ruamel.yaml v0.18.6
│   │       ├── python v3.12.2 (*)
│   │       ├── python v3.12.2 (*)
│   │       ├── python_abi v3.12 (*)
│   │       └── ruamel.yaml.clib v0.2.8
│   │           ├── python v3.12.2 (*)
│   │           ├── python v3.12.2 (*)
│   │           └── python_abi v3.12 (*)
│   ├── python v3.12.2 (*)
│   ├── requests v2.31.0
│   │   ├── certifi v2024.2.2
│   │   │   └── python v3.12.2 (*)
│   │   ├── charset-normalizer v3.3.2
│   │   │   └── python v3.12.2 (*)
│   │   ├── idna v3.6
│   │   │   └── python v3.12.2 (*)
│   │   ├── python v3.12.2 (*)
│   │   └── urllib3 v2.2.1
│   │       ├── brotli-python v1.1.0
│   │       │   ├── libcxx v16.0.6 (*)
│   │       │   ├── python v3.12.2 (*)
│   │       │   ├── python v3.12.2 (*)
│   │       │   └── python_abi v3.12 (*)
│   │       ├── pysocks v1.7.1
│   │       │   └── python v3.12.2 (*)
│   │       └── python v3.12.2 (*)
│   └── ruamel.yaml v0.18.6 (*)
└── tbump v6.9.0
    ├── cli-ui v0.17.2
    │   ├── colorama v0.4.6
    │   │   └── python v3.12.2 (*)
    │   ├── python v3.12.2 (*)
    │   ├── tabulate v0.9.0
    │   │   └── python v3.12.2 (*)
    │   └── unidecode v1.3.8
    │       └── python v3.12.2 (*)
    ├── docopt v0.6.2 (*)
    ├── python v3.12.2 (*)
    ├── schema v0.7.5
    │   ├── contextlib2 v21.6.0
    │   │   └── python v3.12.2 (*)
    │   └── python v3.12.2 (*)
    └── tomlkit v0.12.4
        └── python v3.12.2 (*)
```

**Comment by ruben-arts** [comment] 2024-03-27 08:16
Please create a PR, love to test it out!

**Comment by pavelzw** [comment] 2024-03-27 09:30
How about `pixi tree -d 2` that only prints up to `2` layers deep?

Another idea (maybe a bit crazy / niechy): How about having an additional output format for the DOT Language? This would allow us to create svg plots from the dependency structure. Maybe there are already libraries in rust that do this 😅

**Comment by abkfenris** [comment] 2024-03-27 18:18
I am trying really hard not to get nerd sniped by DOT formatting here (since I've already failed at getting nerd sniped by learning Rust and trying to contribute to Pixi)...let me try to get basic functionality in first. 

I think the format is simple enough that I wouldn't need to bring another library in though.

**Comment by abkfenris** [comment] 2024-03-28 01:52
Ok, have fun #1069

**Closed** 2024-04-03 13:46 UTC
