### ISSUE TITLE
Provide (near) full isolation (inherit just enough from the outside environment to make pixi function).

### ISSUE THREAD

**Issue by kszlim** [prefix-dev/pixi#344] opened 2023-09-18 21:42 UTC
### Problem description

For example PATH is polluted by anything the user might've globally set, perhaps we should have an option in pixi shell to allow near full isolation. Ideally any user can install pixi, use an environment and we can be guaranteedto have a fully reproducible environment without relying on any system toolchains/files.

**Comment by baszalmstra** [comment] 2023-09-19 04:54
This is a good idea and a duplicate of https://github.com/prefix-dev/pixi/issues/289

Closing in favor of that issue.

**Closed** 2023-09-19 04:54 UTC
Labels: duplicate, enhancement
