### ISSUE TITLE
pixi file-related functions stuck after failed package install

### ISSUE THREAD

**Issue by chameroy** [prefix-dev/pixi#2758] opened 2024-12-22 16:13 UTC
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
[project]
channels = ["conda-forge"]
description = "Add a short description here"
name = "python-3.13"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.13.*"
seaborn = ">=0.13.2,<0.14"
scikit-learn = ">=1.6.0,<2"
scikit-image = ">=0.24.0,<0.25"
polars = ">=1.17.1,<2"
opencv = "*"
```

### Issue description

After a failed package install, I was unable to perform any other functions using `pixi` related to package management. Any package-related command I ran resulted in a replay of the failed install attempt. In the above `pixi.toml`, I attempted to install `opencv`, and the install failed due to unmet requirements. Following that, I was unable to install any other packages or even view the installed packages using `pixi list`. To get out of this issue, I had to remove the `opencv` entry from `pixi.toml` either manually or using `pixi remove opencv`.

I've been able to reproduce this issue under Windows 11, Fedora 41 (WSL), and Ubuntu 24.04 LTS (WSL).

### Expected behavior

I would expect that after a failed package install, I would be able to continue performing other tasks using `pixi` (installing packages, listing packages, etc.) without having to edit `pixi.toml` or 'remove' a package that failed to install.

**Comment by seembha** [comment] 2024-12-23 07:07
I was about to report the exact same issue and found this open case. Since the installation/addition failed and the environment didn't change, I would expect the manifest file to be unchanged as well. This would leave the pixi generated manifest file in a good state always.

**Comment by ruben-arts** [comment] 2024-12-23 07:30
Hey thanks for the report, this is a duplicate of: https://github.com/prefix-dev/pixi/issues/2516 and I've been working on a workaround in https://github.com/prefix-dev/pixi/pull/2756. Will close this as duplicate

**Closed by ruben-arts** 2024-12-23 07:30 UTC

**Comment by chameroy** [comment] 2024-12-30 05:27
Sorry for the duplicate. I failed to find the open case when I was checking to see if what I was experiencing had been reported.
