### ISSUE TITLE
Wrong previous version while updating

### ISSUE THREAD

**Issue by Okroshiashvili** [prefix-dev/pixi#1790] opened 2024-08-12 08:38 UTC
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
pixi self-update

```

### Issue description

Few days ago I have run `pixi self-update` to have version 0.27.
This morning I run same command and got this previous version

<img width="373" alt="image" src="https://github.com/user-attachments/assets/0fa70cdc-79b8-4cd9-8e87-a322289f70d7">

### Expected behavior

I expected that the previous version should be 0.27

**Comment by baszalmstra** [comment] 2024-08-12 08:43
Thanks for taking the time to create an issue. Fortunately, this is a duplicate of https://github.com/prefix-dev/pixi/issues/1768 and has been fixed.

**Closed by baszalmstra** 2024-08-12 08:43 UTC
Labels: bug

**Comment by Okroshiashvili** [comment] 2024-08-12 11:26
Thanks @baszalmstra . That was super fast. I missed that the issue was already reported
