### ISSUE TITLE
Pixi does not freeze version number for PyPI package installs

### ISSUE THREAD

**Issue by SeanPedersen** [prefix-dev/pixi#1476] opened 2024-06-04 17:06 UTC
### Problem description

When installing a package via PyPI, pixi does not freeze the installed version number (as it does for conda).
`pixi add --pypi polars`
results in
`polars = "*"`

whereas
`pixi add polars`
results in
`polars = ">=0.20.31,<0.21"`

**Comment by olivier-lacroix** [comment] 2024-06-04 19:16
You are correct. I believe this is a duplicate of https://github.com/prefix-dev/pixi/issues/1409

**Comment by ruben-arts** [comment] 2024-06-05 06:27
Closing in favor of #1409

**Closed by ruben-arts** 2024-06-05 06:27 UTC
Labels: enhancement
