### ISSUE TITLE
Really old ipopt installed by pixi when installing "assimp boost ipopt vtk"

### ISSUE THREAD

**Issue by traversaro** [prefix-dev/pixi#1708] opened 2024-07-31 15:11 UTC
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

Installing assimp boost ipopt vtk result in a really old ipopt being installed:

```shell
pixi init testipopt
cd testipopt
pixi add assimp boost ipopt vtk
pixi list | grep ipopt
```

The ipopt version installed is 3.13.3 instead of the modern 3.14.*

The pixi.toml file is:

~~~toml
[project]
name = "testipopt"
version = "0.1.0"
description = "Add a short description here"
authors = ["Silvio <silvio.traversaro@iit.it>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
assimp = "*"
boost = "*"
ipopt = "*"
vtk = "*"
~~~

### Issue description

While installing a project with these four dependencies, for some reason a really old ipopt got installed. 

### Expected behavior

Installing these packages with conda result correctly in a recent (3.14) ipopt being installed:

~~~
ctraversaro@IITBMP014LW012:~$ conda create -n test assimp boost ipopt vtk
WARNING: A conda environment already exists at '/home/traversaro/miniforge3/envs/test'
Remove existing environment (y/[n])? y

Channels:
 - conda-forge
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
    current version: 24.5.0
    latest version: 24.7.1

Please update conda by running

    $ conda update -n base -c conda-forge conda



## Package Plan ##

  environment location: /home/traversaro/miniforge3/envs/test

  added / updated specs:
    - assimp
    - boost
    - ipopt
    - vtk


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    aiohttp-3.9.5              |  py310h2372a71_0         682 KB  conda-forge
    assimp-5.4.2               |       h2334b4d_0         3.3 MB  conda-forge
    async-timeout-4.0.3        |     pyhd8ed1ab_0          11 KB  conda-forge
    boost-1.84.0               |       hb7f781d_5          16 KB  conda-forge
    ffmpeg-7.0.1               | gpl_h9be9148_104         9.6 MB  conda-forge
    frozenlist-1.4.1           |  py310h2372a71_0          58 KB  conda-forge
    harfbuzz-9.0.0             |       hda332d3_1         1.5 MB  conda-forge
    libass-0.17.1              |       h39113c1_2         123 KB  conda-forge
    libboost-1.84.0            |       h0ccab89_5         2.7 MB  conda-forge
    libboost-devel-1.84.0      |       h00ab1b0_5          39 KB  conda-forge
    libboost-headers-1.84.0    |       ha770c72_5        13.0 MB  conda-forge
    libboost-python-1.84.0     |  py310ha7c98ff_5         119 KB  conda-forge
    libboost-python-devel-1.84.0|  py310hb7f781d_5          20 KB  conda-forge
    libclang-cpp18.1-18.1.8    |default_hf981a13_1        18.3 MB  conda-forge
    libclang13-18.1.8          |default_h9def88c_1        10.5 MB  conda-forge
    libcurl-8.9.0              |       hdb1bdb2_0         406 KB  conda-forge
    libllvm18-18.1.8           |       h8b73ec9_1        36.5 MB  conda-forge
    loguru-0.7.2               |  py310hff52083_1          96 KB  conda-forge
    msgpack-python-1.0.8       |  py310h25c7140_0          95 KB  conda-forge
    multidict-6.0.5            |  py310h2372a71_0          56 KB  conda-forge
    mysql-common-8.3.0         |       h70512c7_5         762 KB  conda-forge
    mysql-libs-8.3.0           |       ha479ceb_5         1.5 MB  conda-forge
    numpy-2.0.1                |  py310hf9f9071_0         7.5 MB  conda-forge
    proj-9.4.1                 |       h54d7996_1         2.9 MB  conda-forge
    qt6-main-6.7.2             |       hb12f9c5_4        44.4 MB  conda-forge
    svt-av1-2.1.2              |       hac33072_0         2.2 MB  conda-forge
    tbb-2021.12.0              |       h434a139_2         188 KB  conda-forge
    tbb-devel-2021.12.0        |       h2069b90_2         1.0 MB  conda-forge
    typing-extensions-4.12.2   |       hd8ed1ab_0          10 KB  conda-forge
    vtk-9.3.1                  |qt_py310hadc0db7_202          20 KB  conda-forge
    vtk-base-9.3.1             |qt_py310ha949da1_202        44.0 MB  conda-forge
    vtk-io-ffmpeg-9.3.1        |qt_py310he1e5eab_202          77 KB  conda-forge
    yarl-1.9.4                 |  py310h2372a71_0         111 KB  conda-forge
    ------------------------------------------------------------
                                           Total:       201.7 MB

The following NEW packages will be INSTALLED:

  _libgcc_mutex      conda-forge/linux-64::_libgcc_mutex-0.1-conda_forge
  _openmp_mutex      conda-forge/linux-64::_openmp_mutex-4.5-2_gnu
  aiohttp            conda-forge/linux-64::aiohttp-3.9.5-py310h2372a71_0
  aiosignal          conda-forge/noarch::aiosignal-1.3.1-pyhd8ed1ab_0
  alsa-lib           conda-forge/linux-64::alsa-lib-1.2.12-h4ab18f5_0
  ampl-mp            conda-forge/linux-64::ampl-mp-3.1.0-h2cc385e_1006
  aom                conda-forge/linux-64::aom-3.9.1-hac33072_0
  assimp             conda-forge/linux-64::assimp-5.4.2-h2334b4d_0
  async-timeout      conda-forge/noarch::async-timeout-4.0.3-pyhd8ed1ab_0
  attrs              conda-forge/noarch::attrs-23.2.0-pyh71513ae_0
  blosc              conda-forge/linux-64::blosc-1.21.6-hef167b5_0
  boost              conda-forge/linux-64::boost-1.84.0-hb7f781d_5
  bzip2              conda-forge/linux-64::bzip2-1.0.8-h4bc722e_7
  c-ares             conda-forge/linux-64::c-ares-1.32.3-h4bc722e_0
  ca-certificates    conda-forge/linux-64::ca-certificates-2024.7.4-hbcca054_0
  cairo              conda-forge/linux-64::cairo-1.18.0-hebfffa5_3
  dav1d              conda-forge/linux-64::dav1d-1.2.1-hd590300_0
  dbus               conda-forge/linux-64::dbus-1.13.6-h5008d03_3
  double-conversion  conda-forge/linux-64::double-conversion-3.3.0-h59595ed_0
  eigen              conda-forge/linux-64::eigen-3.4.0-h00ab1b0_0
  expat              conda-forge/linux-64::expat-2.6.2-h59595ed_0
  ffmpeg             conda-forge/linux-64::ffmpeg-7.0.1-gpl_h9be9148_104
  font-ttf-dejavu-s~ conda-forge/noarch::font-ttf-dejavu-sans-mono-2.37-hab24e00_0
  font-ttf-inconsol~ conda-forge/noarch::font-ttf-inconsolata-3.000-h77eed37_0
  font-ttf-source-c~ conda-forge/noarch::font-ttf-source-code-pro-2.038-h77eed37_0
  font-ttf-ubuntu    conda-forge/noarch::font-ttf-ubuntu-0.83-h77eed37_2
  fontconfig         conda-forge/linux-64::fontconfig-2.14.2-h14ed4e7_0
  fonts-conda-ecosy~ conda-forge/noarch::fonts-conda-ecosystem-1-0
  fonts-conda-forge  conda-forge/noarch::fonts-conda-forge-1-0
  freetype           conda-forge/linux-64::freetype-2.12.1-h267a509_2
  fribidi            conda-forge/linux-64::fribidi-1.0.10-h36c2ea0_0
  frozenlist         conda-forge/linux-64::frozenlist-1.4.1-py310h2372a71_0
  gettext            conda-forge/linux-64::gettext-0.22.5-h59595ed_2
  gettext-tools      conda-forge/linux-64::gettext-tools-0.22.5-h59595ed_2
  gl2ps              conda-forge/linux-64::gl2ps-1.4.2-hae5d5c5_1
  glew               conda-forge/linux-64::glew-2.1.0-h9c3ff4c_2
  gmp                conda-forge/linux-64::gmp-6.3.0-hac33072_2
  gnutls             conda-forge/linux-64::gnutls-3.7.9-hb077bed_0
  graphite2          conda-forge/linux-64::graphite2-1.3.13-h59595ed_1003
  harfbuzz           conda-forge/linux-64::harfbuzz-9.0.0-hda332d3_1
  hdf4               conda-forge/linux-64::hdf4-4.2.15-h2a13503_7
  hdf5               conda-forge/linux-64::hdf5-1.14.3-nompi_hdf9ad27_105
  icu                conda-forge/linux-64::icu-75.1-he02047a_0
  idna               conda-forge/noarch::idna-3.7-pyhd8ed1ab_0
  ipopt              conda-forge/linux-64::ipopt-3.14.16-h3696c94_4
  jsoncpp            conda-forge/linux-64::jsoncpp-1.9.5-h4bd325d_1
  keyutils           conda-forge/linux-64::keyutils-1.6.1-h166bdaf_0
  krb5               conda-forge/linux-64::krb5-1.21.3-h659f571_0
  lame               conda-forge/linux-64::lame-3.100-h166bdaf_1003
  ld_impl_linux-64   conda-forge/linux-64::ld_impl_linux-64-2.40-hf3520f5_7
  lerc               conda-forge/linux-64::lerc-4.0.0-h27087fc_0
  libabseil          conda-forge/linux-64::libabseil-20240116.2-cxx17_he02047a_1
  libaec             conda-forge/linux-64::libaec-1.1.3-h59595ed_0
  libasprintf        conda-forge/linux-64::libasprintf-0.22.5-h661eb56_2
  libasprintf-devel  conda-forge/linux-64::libasprintf-devel-0.22.5-h661eb56_2
  libass             conda-forge/linux-64::libass-0.17.1-h39113c1_2
  libblas            conda-forge/linux-64::libblas-3.9.0-23_linux64_openblas
  libboost           conda-forge/linux-64::libboost-1.84.0-h0ccab89_5
  libboost-devel     conda-forge/linux-64::libboost-devel-1.84.0-h00ab1b0_5
  libboost-headers   conda-forge/linux-64::libboost-headers-1.84.0-ha770c72_5
  libboost-python    conda-forge/linux-64::libboost-python-1.84.0-py310ha7c98ff_5
  libboost-python-d~ conda-forge/linux-64::libboost-python-devel-1.84.0-py310hb7f781d_5
  libcblas           conda-forge/linux-64::libcblas-3.9.0-23_linux64_openblas
  libclang-cpp18.1   conda-forge/linux-64::libclang-cpp18.1-18.1.8-default_hf981a13_1
  libclang13         conda-forge/linux-64::libclang13-18.1.8-default_h9def88c_1
  libcups            conda-forge/linux-64::libcups-2.3.3-h4637d8d_4
  libcurl            conda-forge/linux-64::libcurl-8.9.0-hdb1bdb2_0
  libdeflate         conda-forge/linux-64::libdeflate-1.20-hd590300_0
  libdrm             conda-forge/linux-64::libdrm-2.4.122-h4ab18f5_0
  libedit            conda-forge/linux-64::libedit-3.1.20191231-he28a2e2_2
  libev              conda-forge/linux-64::libev-4.33-hd590300_2
  libexpat           conda-forge/linux-64::libexpat-2.6.2-h59595ed_0
  libffi             conda-forge/linux-64::libffi-3.4.2-h7f98852_5
  libgcc-ng          conda-forge/linux-64::libgcc-ng-14.1.0-h77fa898_0
  libgettextpo       conda-forge/linux-64::libgettextpo-0.22.5-h59595ed_2
  libgettextpo-devel conda-forge/linux-64::libgettextpo-devel-0.22.5-h59595ed_2
  libgfortran-ng     conda-forge/linux-64::libgfortran-ng-14.1.0-h69a702a_0
  libgfortran5       conda-forge/linux-64::libgfortran5-14.1.0-hc5f4f2c_0
  libglib            conda-forge/linux-64::libglib-2.80.3-h8a4344b_1
  libglu             conda-forge/linux-64::libglu-9.0.0-ha6d2627_1004
  libgomp            conda-forge/linux-64::libgomp-14.1.0-h77fa898_0
  libhwloc           conda-forge/linux-64::libhwloc-2.11.0-default_h5622ce7_1000
  libiconv           conda-forge/linux-64::libiconv-1.17-hd590300_2
  libidn2            conda-forge/linux-64::libidn2-2.3.7-hd590300_0
  libjpeg-turbo      conda-forge/linux-64::libjpeg-turbo-3.0.0-hd590300_1
  liblapack          conda-forge/linux-64::liblapack-3.9.0-23_linux64_openblas
  libllvm18          conda-forge/linux-64::libllvm18-18.1.8-h8b73ec9_1
  libnetcdf          conda-forge/linux-64::libnetcdf-4.9.2-nompi_h135f659_114
  libnghttp2         conda-forge/linux-64::libnghttp2-1.58.0-h47da74e_1
  libnsl             conda-forge/linux-64::libnsl-2.0.1-hd590300_0
  libogg             conda-forge/linux-64::libogg-1.3.5-h4ab18f5_0
  libopenblas        conda-forge/linux-64::libopenblas-0.3.27-pthreads_hac2b453_1
  libopenvino        conda-forge/linux-64::libopenvino-2024.2.0-h2da1b83_1
  libopenvino-auto-~ conda-forge/linux-64::libopenvino-auto-batch-plugin-2024.2.0-hb045406_1
  libopenvino-auto-~ conda-forge/linux-64::libopenvino-auto-plugin-2024.2.0-hb045406_1
  libopenvino-heter~ conda-forge/linux-64::libopenvino-hetero-plugin-2024.2.0-h5c03a75_1
  libopenvino-intel~ conda-forge/linux-64::libopenvino-intel-cpu-plugin-2024.2.0-h2da1b83_1
  libopenvino-intel~ conda-forge/linux-64::libopenvino-intel-gpu-plugin-2024.2.0-h2da1b83_1
  libopenvino-intel~ conda-forge/linux-64::libopenvino-intel-npu-plugin-2024.2.0-he02047a_1
  libopenvino-ir-fr~ conda-forge/linux-64::libopenvino-ir-frontend-2024.2.0-h5c03a75_1
  libopenvino-onnx-~ conda-forge/linux-64::libopenvino-onnx-frontend-2024.2.0-h07e8aee_1
  libopenvino-paddl~ conda-forge/linux-64::libopenvino-paddle-frontend-2024.2.0-h07e8aee_1
  libopenvino-pytor~ conda-forge/linux-64::libopenvino-pytorch-frontend-2024.2.0-he02047a_1
  libopenvino-tenso~ conda-forge/linux-64::libopenvino-tensorflow-frontend-2024.2.0-h39126c6_1
  libopenvino-tenso~ conda-forge/linux-64::libopenvino-tensorflow-lite-frontend-2024.2.0-he02047a_1
  libopus            conda-forge/linux-64::libopus-1.3.1-h7f98852_1
  libpciaccess       conda-forge/linux-64::libpciaccess-0.18-hd590300_0
  libpng             conda-forge/linux-64::libpng-1.6.43-h2797004_0
  libpq              conda-forge/linux-64::libpq-16.3-ha72fbe1_0
  libprotobuf        conda-forge/linux-64::libprotobuf-4.25.3-h08a7969_0
  libscotch          conda-forge/linux-64::libscotch-7.0.4-h2fe6a88_5
  libspral           conda-forge/linux-64::libspral-2024.05.08-hdf4021c_2
  libsqlite          conda-forge/linux-64::libsqlite-3.46.0-hde9e2c9_0
  libssh2            conda-forge/linux-64::libssh2-1.11.0-h0841786_0
  libstdcxx-ng       conda-forge/linux-64::libstdcxx-ng-14.1.0-hc0a3c3a_0
  libtasn1           conda-forge/linux-64::libtasn1-4.19.0-h166bdaf_0
  libtheora          conda-forge/linux-64::libtheora-1.1.1-h4ab18f5_1006
  libtiff            conda-forge/linux-64::libtiff-4.6.0-h1dd3fc0_3
  libunistring       conda-forge/linux-64::libunistring-0.9.10-h7f98852_0
  libuuid            conda-forge/linux-64::libuuid-2.38.1-h0b41bf4_0
  libva              conda-forge/linux-64::libva-2.22.0-hb711507_0
  libvorbis          conda-forge/linux-64::libvorbis-1.3.7-h9c3ff4c_0
  libvpx             conda-forge/linux-64::libvpx-1.14.1-hac33072_0
  libwebp-base       conda-forge/linux-64::libwebp-base-1.4.0-hd590300_0
  libxcb             conda-forge/linux-64::libxcb-1.16-hd590300_0
  libxcrypt          conda-forge/linux-64::libxcrypt-4.4.36-hd590300_1
  libxkbcommon       conda-forge/linux-64::libxkbcommon-1.7.0-h2c5496b_1
  libxml2            conda-forge/linux-64::libxml2-2.12.7-he7c6b58_4
  libzip             conda-forge/linux-64::libzip-1.10.1-h2629f0a_3
  libzlib            conda-forge/linux-64::libzlib-1.3.1-h4ab18f5_1
  loguru             conda-forge/linux-64::loguru-0.7.2-py310hff52083_1
  lz4-c              conda-forge/linux-64::lz4-c-1.9.4-hcb278e6_0
  metis              conda-forge/linux-64::metis-5.1.0-h59595ed_1007
  msgpack-python     conda-forge/linux-64::msgpack-python-1.0.8-py310h25c7140_0
  multidict          conda-forge/linux-64::multidict-6.0.5-py310h2372a71_0
  mumps-include      conda-forge/linux-64::mumps-include-5.7.2-ha770c72_0
  mumps-seq          conda-forge/linux-64::mumps-seq-5.7.2-h6e8dedb_0
  mysql-common       conda-forge/linux-64::mysql-common-8.3.0-h70512c7_5
  mysql-libs         conda-forge/linux-64::mysql-libs-8.3.0-ha479ceb_5
  ncurses            conda-forge/linux-64::ncurses-6.5-h59595ed_0
  nettle             conda-forge/linux-64::nettle-3.9.1-h7ab15ed_0
  nlohmann_json      conda-forge/linux-64::nlohmann_json-3.11.3-h59595ed_0
  numpy              conda-forge/linux-64::numpy-2.0.1-py310hf9f9071_0
  ocl-icd            conda-forge/linux-64::ocl-icd-2.3.2-hd590300_1
  openh264           conda-forge/linux-64::openh264-2.4.1-h59595ed_0
  openssl            conda-forge/linux-64::openssl-3.3.1-h4bc722e_2
  p11-kit            conda-forge/linux-64::p11-kit-0.24.1-hc5aa10d_0
  pcre2              conda-forge/linux-64::pcre2-10.44-h0f59acf_0
  pip                conda-forge/noarch::pip-24.1.2-pyhd8ed1ab_0
  pixman             conda-forge/linux-64::pixman-0.43.2-h59595ed_0
  proj               conda-forge/linux-64::proj-9.4.1-h54d7996_1
  pthread-stubs      conda-forge/linux-64::pthread-stubs-0.4-h36c2ea0_1001
  pugixml            conda-forge/linux-64::pugixml-1.14-h59595ed_0
  python             conda-forge/linux-64::python-3.10.14-hd12c33a_0_cpython
  python_abi         conda-forge/linux-64::python_abi-3.10-4_cp310
  qt6-main           conda-forge/linux-64::qt6-main-6.7.2-hb12f9c5_4
  readline           conda-forge/linux-64::readline-8.2-h8228510_1
  snappy             conda-forge/linux-64::snappy-1.2.1-ha2e4443_0
  sqlite             conda-forge/linux-64::sqlite-3.46.0-h6d4b2fc_0
  svt-av1            conda-forge/linux-64::svt-av1-2.1.2-hac33072_0
  tbb                conda-forge/linux-64::tbb-2021.12.0-h434a139_2
  tbb-devel          conda-forge/linux-64::tbb-devel-2021.12.0-h2069b90_2
  tk                 conda-forge/linux-64::tk-8.6.13-noxft_h4845f30_101
  typing-extensions  conda-forge/noarch::typing-extensions-4.12.2-hd8ed1ab_0
  typing_extensions  conda-forge/noarch::typing_extensions-4.12.2-pyha770c72_0
  tzdata             conda-forge/noarch::tzdata-2024a-h0c530f3_0
  unixodbc           conda-forge/linux-64::unixodbc-2.3.12-h661eb56_0
  utfcpp             conda-forge/linux-64::utfcpp-4.0.5-ha770c72_0
  vtk                conda-forge/linux-64::vtk-9.3.1-qt_py310hadc0db7_202
  vtk-base           conda-forge/linux-64::vtk-base-9.3.1-qt_py310ha949da1_202
  vtk-io-ffmpeg      conda-forge/linux-64::vtk-io-ffmpeg-9.3.1-qt_py310he1e5eab_202
  wayland            conda-forge/linux-64::wayland-1.23.0-h5291e77_0
  wayland-protocols  conda-forge/noarch::wayland-protocols-1.36-hd8ed1ab_0
  wslink             conda-forge/noarch::wslink-2.1.1-pyhd8ed1ab_0
  x264               conda-forge/linux-64::x264-1!164.3095-h166bdaf_2
  x265               conda-forge/linux-64::x265-3.5-h924138e_3
  xcb-util           conda-forge/linux-64::xcb-util-0.4.1-hb711507_2
  xcb-util-cursor    conda-forge/linux-64::xcb-util-cursor-0.1.4-h4ab18f5_2
  xcb-util-image     conda-forge/linux-64::xcb-util-image-0.4.0-hb711507_2
  xcb-util-keysyms   conda-forge/linux-64::xcb-util-keysyms-0.4.1-hb711507_0
  xcb-util-renderut~ conda-forge/linux-64::xcb-util-renderutil-0.3.10-hb711507_0
  xcb-util-wm        conda-forge/linux-64::xcb-util-wm-0.4.2-hb711507_0
  xkeyboard-config   conda-forge/linux-64::xkeyboard-config-2.42-h4ab18f5_0
  xorg-fixesproto    conda-forge/linux-64::xorg-fixesproto-5.0-h7f98852_1002
  xorg-kbproto       conda-forge/linux-64::xorg-kbproto-1.0.7-h7f98852_1002
  xorg-libice        conda-forge/linux-64::xorg-libice-1.1.1-hd590300_0
  xorg-libsm         conda-forge/linux-64::xorg-libsm-1.2.4-h7391055_0
  xorg-libx11        conda-forge/linux-64::xorg-libx11-1.8.9-hb711507_1
  xorg-libxau        conda-forge/linux-64::xorg-libxau-1.0.11-hd590300_0
  xorg-libxdmcp      conda-forge/linux-64::xorg-libxdmcp-1.1.3-h7f98852_0
  xorg-libxext       conda-forge/linux-64::xorg-libxext-1.3.4-h0b41bf4_2
  xorg-libxfixes     conda-forge/linux-64::xorg-libxfixes-5.0.3-h7f98852_1004
  xorg-libxrender    conda-forge/linux-64::xorg-libxrender-0.9.11-hd590300_0
  xorg-libxt         conda-forge/linux-64::xorg-libxt-1.3.0-hd590300_1
  xorg-renderproto   conda-forge/linux-64::xorg-renderproto-0.11.1-h7f98852_1002
  xorg-xextproto     conda-forge/linux-64::xorg-xextproto-7.3.0-h0b41bf4_1003
  xorg-xproto        conda-forge/linux-64::xorg-xproto-7.0.31-h7f98852_1007
  xz                 conda-forge/linux-64::xz-5.2.6-h166bdaf_0
  yarl               conda-forge/linux-64::yarl-1.9.4-py310h2372a71_0
  zlib               conda-forge/linux-64::zlib-1.3.1-h4ab18f5_1
  zstd               conda-forge/linux-64::zstd-1.5.6-ha6fb4c9_0


Proceed ([y]/n)? n


CondaSystemExit: Exiting.

~~~

**Comment by traversaro** [comment] 2024-07-31 15:11
System info:

~~~
traversaro@IITBMP014LW012:~$ conda info

     active environment : None
            shell level : 0
       user config file : /home/traversaro/.condarc
 populated config files : /home/traversaro/miniforge3/.condarc
                          /home/traversaro/.condarc
          conda version : 24.5.0
    conda-build version : 24.5.1
         python version : 3.10.14.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=skylake
                          __conda=24.5.0=0
                          __cuda=12.3=0
                          __glibc=2.39=0
                          __linux=5.15.153.1=0
                          __unix=0=0
       base environment : /home/traversaro/miniforge3  (writable)
      conda av data dir : /home/traversaro/miniforge3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /home/traversaro/miniforge3/pkgs
                          /home/traversaro/.conda/pkgs
       envs directories : /home/traversaro/miniforge3/envs
                          /home/traversaro/.conda/envs
               platform : linux-64
             user-agent : conda/24.5.0 requests/2.31.0 CPython/3.10.14 Linux/5.15.153.1-microsoft-standard-WSL2 ubuntu/24.04 glibc/2.39 solver/libmamba conda-libmamba-solver/24.1.0 libmambapy/1.5.8
                UID:GID : 1002:1002
             netrc file : None
           offline mode : False


traversaro@IITBMP014LW012:~$ pixi info
      Pixi version: 0.26.1
          Platform: linux-64
  Virtual packages: __unix=0=0
                  : __linux=5.15.153.1=0
                  : __glibc=2.39=0
                  : __cuda=12.3=0
                  : __archspec=1=skylake
         Cache dir: /home/traversaro/.cache/rattler/cache
      Auth storage: /home/traversaro/.rattler/credentials.json
~~~

**Comment by ruben-arts** [comment] 2024-08-05 13:48
I think I found the culprit. Because of some requirements fighting over the Zlib you cant combine `ipopt 3.14.0` and `assimp 5.4.2`. So it's either a lower version of `assimp` of an older version of `ipopt`. 

Result of `rattler create ipopt==3.14 assimp==5.4.2  vtk boost --dry-run -c https://fast.prefix.dev/conda-forge`:
```
Error: Cannot solve the request because of: The following packages are incompatible
├─ ipopt ==3.14 can be installed with any of the following options:
│  └─ ipopt 3.14.0 would require
│     └─ mumps-seq >=5.2.1,<5.2.2.0a0, which can be installed with any of the following options:
│        ├─ mumps-seq 5.2.1 | 5.2.1 | 5.2.1 | 5.2.1 | 5.2.1 | 5.2.1 | 5.2.1 would require
│        │  └─ scotch >=6.0.9,<6.1.0a0, which can be installed with any of the following options:
│        │     └─ scotch 6.0.9 | 6.0.9 | 6.0.9 | 6.0.9 | 6.0.9 | 6.0.9 | 6.0.9 | 6.0.9 would require
│        │        └─ zlib >=1.2.11,<1.3.0a0, which can be installed with any of the following options:
│        │           └─ zlib 1.2.11 | 1.2.11 | 1.2.11 | 1.2.11 | 1.2.11 | 1.2.11 | 1.2.11 | 1.2.11 | 1.2.11 | 1.2.11 | 1.2.11 | 1.2.11 | 1.2.11 | 1.2.11 | 1.2.11 | 1.2.11 | 1.2.12 | 1.2.12 | 1.2.12 | 1.2.12 | 1.2.12 | 1.2.13 | 1.2.13 | 1.2.13
│        ├─ mumps-seq 5.2.1 | 5.2.1 | 5.2.1 | 5.2.1 | 5.2.1 would require
│        │  └─ scotch >=6.0.8,<6.1.0a0, which can be installed with any of the following options:
│        │     └─ scotch 6.0.8 | 6.0.8 | 6.0.8 | 6.0.8 would require
│        │        └─ zlib >=1.2.11,<1.3.0a0, which can be installed with any of the following options:
│        ├─ mumps-seq 5.2.1 would require
│        │  └─ scotch >=6.0.7,<6.1.0a0, which can be installed with any of the following options:
│        │     └─ scotch 6.0.7 | 6.0.7 would require
│        │        └─ zlib >=1.2.11,<1.3.0a0, which can be installed with any of the following options:
│        └─ mumps-seq 5.2.1 would require
│           └─ scotch >=6.0.6,<6.1.0a0, which can be installed with any of the following options:
│              └─ scotch 6.0.6 | 6.0.6 | 6.0.6 | 6.0.6 | 6.0.6 | 6.0.6 | 6.0.6 | 6.0.6 | 6.0.6 | 6.0.6 | 6.0.6 | 6.0.6 would require
│                 └─ zlib >=1.2.11,<1.3.0a0, which can be installed with any of the following options:
└─ assimp ==5.4.2 cannot be installed because there are no viable options:
   └─ assimp 5.4.2 would require
      └─ libzlib >=1.3.1,<2.0a0, which cannot be installed because there are no viable options:
         └─ libzlib 1.3.1 | 1.3.1 would constrain
            └─ zlib ==1.3.1 *_0 , which conflicts with any installable versions previously reported
```

Closing as I believe this is not something related to `pixi` but more to the solver heuristic and I don't think its wrong.

**Closed by ruben-arts** 2024-08-05 13:48 UTC
Labels: bug

**Comment by traversaro** [comment] 2024-08-05 22:58
Why do you want to install ipopt 3.14.0? conda correctly installs the latest ipopt 3.14.16 .

**Comment by ruben-arts** [comment] 2024-08-06 05:25
I retried with `3.14.16` and the same situation for another package happens.
Here `libhwloc` gets limited to `2.11.0` where the version with `3.13.3` gets `2.11.1`.

You say that getting the higher `ipopt` would be correct but why is that the case? As in what heuristic would make that "correct"?

@baszalmstra am I missing something here?

**Comment by traversaro** [comment] 2024-08-06 08:03
I may be just a victim of [Hyrum's Law](https://www.hyrumslaw.com/), but my mental model for conda installation heuristics has always been "maximize the versions of the packages I am installing explictly". 

In particular, it may be a personal preference, but as I am installing explicitly assimp ipopt boost vtk, it really suprise me that the algorithm tries to maximize the version of libhwloc installed, that is a library that I am not installing explicitly.

**Comment by traversaro** [comment] 2024-08-06 08:04
(unrelated note: @ruben-arts  how can install the `rattler` command so that I can run your debug commands?)

**Comment by traversaro** [comment] 2024-08-06 08:05
> (unrelated note: @ruben-arts how can install the `rattler` command so that I can run your debug commands?)

Problem solved, I just need to follow https://github.com/conda-incubator/rattler?tab=readme-ov-file#give-it-a-try .

**Comment by ruben-arts** [comment] 2024-08-06 09:35
> that is a library that I am not installing explicitly.

That is a good point. @baszalmstra what do you think about that?

**Comment by traversaro** [comment] 2024-08-06 10:11
So everything boils down to me forgetting to merge https://github.com/conda-forge/spral-feedstock/pull/16 . However, I can wait to merge if you want to debug the counter-intuitive behavior.

**Comment by baszalmstra** [comment] 2024-08-06 10:19
Currently, the solver heuristics do not take into account whether a package was explicitly requested or not. I think we would be able to add that although it might also have adverse effects on performance. 

I created an [issue for resolvo](https://github.com/mamba-org/resolvo/issues/60) so we can keep track of this.

**Comment by traversaro** [comment] 2024-08-06 10:21
Thanks @baszalmstra ! I will follow up there.

**Comment by traversaro** [comment] 2024-08-06 14:37
> So everything boils down to me forgetting to merge [conda-forge/spral-feedstock#16](https://github.com/conda-forge/spral-feedstock/pull/16) . However, I can wait to merge if you want to debug the counter-intuitive behavior.

As I guess anyhow this will take time to solve and the problem is well understood, I will merge https://github.com/conda-forge/spral-feedstock/pull/16 .

**Comment by baszalmstra** [comment] 2024-08-06 14:48
@traversaro Totally fine! I already implemented a fix where I have a repro for this behavior: https://github.com/mamba-org/resolvo/pull/61. We also have this feature in rattler-solve that we can filter "newer" records so reproducing this should be "easy". :)
