### ISSUE TITLE
CUDA virtual package is not detected on Debian

### ISSUE THREAD

**Issue by twrightsman** [prefix-dev/pixi#294] opened 2023-08-23 17:52 UTC
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```
$ pixi info
pixi 0.2.0

Platform            : linux-64
Virtual packages    : __unix=0=0
                    : __linux=5.10.0=0
                    : __glibc=2.31=0
                    : __archspec=1=x86_64
```

### Issue description

`pixi-x86_64-unknown-linux-musl` v0.2.0 from the GitHub release fails to detect CUDA on my Debian system.

Strangely, building `pixi` v0.2.0 from source on my system correctly detects CUDA...

### Expected behavior

`__cuda` to show up under virtual packages.

**Comment by baszalmstra** [comment] 2023-08-23 21:20
I think this issue is caused by pixi being statically linked against musl libc and musl libc not supporting dlopen. We use dlopen to load the nvml library and read the available cuda version. But if this is not supported we’ll have to use another method..

**Comment by baszalmstra** [comment] 2023-08-23 21:28
No thats also not entirely true.. Musl libc does support dlopen. Ill add more logging to see whatsup.

**Comment by baszalmstra** [comment] 2023-08-24 08:05
So after some research I think our current approach (loading nvidia nvml dynamically) will never work for our statically linked pixi binary. We will try implementing CUDA version detection using another mechanic.

**Comment by baszalmstra** [comment] 2023-08-24 09:27
I created [this WIP PR](https://github.com/prefix-dev/pixi/pull/298) so we can test it :)

**Comment by baszalmstra** [comment] 2023-08-24 10:08
I can confirm that at least on WSL this works! 👍 
@twrightsman Would you be able to try out the artifact from the build pipeline in [this WIP PR](https://github.com/prefix-dev/pixi/pull/298)?

**Comment by baszalmstra** [comment] 2023-08-24 13:36
You most likely need to add a system_requirement for this. Pixi doesn't use the virtual packages from your system but instead relies on predetermined virtual packages from a "reference machine". This ensures that if you solve the environment on your machine it will be same as on mine. However, my machine may not have a CUDA driver so the "reference machine" doesn't provide the `__cuda` virtual package. You can however specify through `system-requirements` that your project requires cuda:

```toml
[system-requirements]
cuda = "12.2"
```

This will indicate that your project requires at least cuda 12.2 to function. You should be able to add the dependency then. 

In the future we want to extend this behavior so that you can have different dependencies based on whether or not someone has cuda or not.

**Comment by baszalmstra** [comment] 2023-08-24 13:37
Im closing this issue for now, the next release of pixi (most likely 0.3.0) will have the fix included.

If you still have issues with cuda after adding the system requirement feel free to open another issue.

**Closed by baszalmstra** 2023-08-24 13:37 UTC
Labels: bug

**Comment by ephemer** [comment] 2024-10-20 13:33
How can we set

```
[system-requirements]
cuda = "12.2"
```

just for linux targets? We have mac a development environment and linux prod. Adding the system-requirements like this breaks mac, and `[target.linux-64.system-requirements]` isn't accepted

@baszalmstra

**Comment by baszalmstra** [comment] 2024-10-20 14:11
Thats strange, from my understanding that should work! What is the error you get?

**Comment by ephemer** [comment] 2024-10-21 07:41
It says there's no such key as "target.linux-64.system-requirements". And just putting it in the top level namespace leads to the error (on Mac) that the virtual package __cuda is missing
