### ISSUE TITLE
Editable install of package failed to update `importlib.metadata.version`

### ISSUE THREAD

**Issue by lucascolley** [prefix-dev/pixi#2139] opened 2024-09-25 13:12 UTC
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

`pyproject.toml`: https://github.com/data-apis/array-api-extra/blob/main/pyproject.toml

### Issue description

Sorry for the lack of reproducible example here, this is a bit convoluted. I asked this on Discord and @ruben-arts directed me to open an issue here.

I was (rebase) pulling the latest 14 commits from https://github.com/data-apis/array-api-extra/commits/main/ into another branch. In the process there was a merge conflict with the lockfile so I deleted it to complete the rebase. After rebasing, I used `pixi update` to regenerate the lockfile.

As part of the rebase, the version of my package updated from `'0.1.dev0'` to `'0.1.2.dev0'`. This version is updated dynamically.

After the rebase and update, `pixi ls` correctly showed the new version of the package:

```
Environment: dev
Package                        Version     Build                 Size       Kind   Source
...
array_api_extra                0.1.2.dev0                                   pypi   . (editable)
```

However, `importlib.metadata.version` failed to update:

```
# running ipython in the same env
In [1]: import importlib

In [2]: importlib.metadata.version("array_api_extra")
Out[2]: '0.1.dev0'
```

`pixi update` failed to resolve the issue. However:

```
pixi clean
pixi update
pixi shell -e dev
```

fixed the issue.

### Expected behavior

It would be nice if `pixi update` alone fixed the issue and loaded the updated version in IPython.

**Comment by rgommers** [comment] 2024-10-15 08:24
I'm not sure this is a bug. `importlib.metadata.version` reads the `.dist-info` metadata of a package, which is only written when a build frontend (e.g., `uv` or `pip`) invokes a build backend to produce a wheel. Which is typically expensive and not what you want for an already-installed editable install.

It looks like what is happening here is:
1. For `pixi update`, dependencies are updated but `uv` isn't invoked to build an editable install from scratch.
2. For `pixi clean && pixi update && pixi shell -e dev` the clean step actually removes `.dist-info` (because it's part of the environment), so `pixi update` probably detects that the project is no longer installed as editable and then has to do a full reinstall.

I suspect (1) is by design, and everything is working as intended. Also note that for editable installs with say `pip` in virtual env, the same happens - if you update the version of your package, that won't be reflected in what `importlib.metadata.version` returns until you explicitly re-run `pip install . -e`.

**Comment by lucascolley** [comment] 2024-10-27 23:50
Thanks Ralf. I was about to close this issue, although maybe some flag to `pixi update` to also update editable installs could be considered? If I am the only person who has hit this, though, probably fine to just close.

**Comment by ruben-arts** [comment] 2024-10-28 08:33
This in [this](https://github.com/prefix-dev/pixi/issues/1233) conversation we're discussing the `--force-reinstall` (name tbd) which will happen. So I'll close this in favor of that. Thanks @rgommers!

**Closed** 2024-10-28 21:08 UTC
Labels: :lady_beetle: bug, :snake: pypi
