### ISSUE TITLE
Introduce an option to disable PS1 shell injection

### ISSUE THREAD

**Issue by thomasjpfan** [prefix-dev/pixi#899] opened 2024-03-02 02:12 UTC
### Problem description

Currently `pixi shell` injects the virtualenv into the prompt. For my shell configuration, it looks like this:

```
(pixi-hello-world)
~/Desktop/pixi-hello-world via 🅒 pixi-hello-world
❯
```

I have configured my shell to display the `conda` environment, so I do not need the extra `(pixi-hello-world)`. Can there be an option to disable the `PS1` injection?

**Comment by chawyehsu** [comment] 2024-03-03 02:02
Duplicate of #523, tracking in #172

**Closed** 2024-03-14 12:19 UTC
Labels: enhancement
