### ISSUE TITLE
pixi global doesn't respect casing of exposed binaries

### ISSUE THREAD

**Issue by beenje** [prefix-dev/pixi#2520] opened 2024-11-19 17:00 UTC
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
$ docker run --rm -it ghcr.io/prefix-dev/pixi:latest bash
root@32eb3bb15562:/# pixi self-update
Pixi will be updated from 0.36.0 to 0.37.0
Pixi archive downloaded.
Pixi archive uncompressed.
Pixi has been updated to version 0.37.0.
root@32eb3bb15562:/# pixi --version
pixi 0.37.0
root@32eb3bb15562:/# pixi global install pytango-db
Global environments as specified in '/root/.pixi/manifests/pixi-global.toml'
└── pytango-db: 0.3.0 (installed)
    └─ exposes: pydatabaseds
```

pixi exposes `pydatabaseds` in lower case, while the binary is `PyDatabaseds` with a capital `P` and `D`.

```shell
root@32eb3bb15562:/# cat /root/.pixi/bin/trampoline_configuration/pydatabaseds.json
{
  "exe": "/root/.pixi/envs/pytango-db/bin/PyDatabaseds",
  "path": "/root/.pixi/envs/pytango-db/bin",
  "env": {
    "PATH": "/root/.pixi/envs/pytango-db/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
    "CONDA_PREFIX": "/root/.pixi/envs/pytango-db"
  }
}
```

Trying to force the casing with `--expose` doesn't work:

```shell
root@32eb3bb15562:/# pixi global install --expose PyDatabaseds=PyDatabaseds  pytango-db
  x Couldn't install pytango-db
  |-> Failed to add executables for environment: pytango-db
  `-> Couldn't find executable PyDatabaseds in /root/.pixi/envs/pytango-db, found these executables: []
```

### Issue description

pixi global seems to always use lowercase when exposing an executable.

### Expected behavior

I'd expect pixi to follow the original binary casing.

**Comment by olivier-lacroix** [comment] 2024-11-19 23:36
This may be a duplicate of / is related to https://github.com/prefix-dev/pixi/issues/2478

**Comment by beenje** [comment] 2024-11-20 07:18
> This may be a duplicate of / is related to [#2478](https://github.com/prefix-dev/pixi/issues/2478)

Indeed. Sorry, I searched for issues linked to case sensitivity but missed it.

**Comment by danielnachun** [comment] 2024-11-20 09:17
Actually this issue predates the one I reported.  It is not clear to me if the lack of case sensitivity for the **default** exposed executables was an intentional design decision, possibly motivated by a desire for consistency across platforms given that macOS is case-insensitive, or a bug/oversight.

It would actually be great if `pixi global` just preserved the case of the binaries it exposed, and it would avoid the need for customizing exposed executables just to restore the proper case.  Custom exposed executables however should still respect the case the user specifies in case they need to change it for some reason.

**Comment by Hofer-Julian** [comment] 2024-11-22 16:35
Closed by https://github.com/prefix-dev/pixi/pull/2528

**Closed by Hofer-Julian** 2024-11-22 16:35 UTC
Labels: area:global
