### ISSUE TITLE
PyCharm integration

### ISSUE THREAD

**Issue by jonashaag** [prefix-dev/pixi#189] opened 2023-07-10 08:45 UTC
Here's a Pixi variant of my https://github.com/jonashaag/micromamba-pycharm.

Put this into each `.pixi/` folder as `.pixi/conda`.

```py
#!/usr/bin/env python3

import sys
import json
import subprocess
import yaml
from pathlib import Path

PIXI_ROOT = Path(__file__).parent
PROJECT_ROOT = PIXI_ROOT.parent

ENABLE_LOGGING = True
if ENABLE_LOGGING:
    open("/tmp/conda-wrapper-log", "a").write(str(sys.argv[1:]) + "\n")

if sys.argv[1:4] == ["info", "--envs", "--json"]:
    print(
        json.dumps(
            {
                "envs_dirs": [str(PIXI_ROOT)],
                "conda_prefix": str(PIXI_ROOT),
                "envs": [str(PIXI_ROOT / "env")],
            }
        )
    )
elif sys.argv[1] == "list":
    lockfile = yaml.safe_load((PROJECT_ROOT / "pixi.lock").read_text())
    for pkg in sorted(lockfile["package"], key=lambda pkg: pkg["name"]):
        print(pkg["name"], pkg["version"], pkg["build"], "fake-channel")
elif sys.argv[1] == "run":
    assert sys.argv[4] == "--no-capture-output"
    subprocess.run(["pixi", "run", *sys.argv[5:]])
else:
    raise NotImplementedError(str(sys.argv[1:]))
```

**Comment by baszalmstra** [comment] 2023-08-14 08:00
How do you think we could integrate this into pixi itself?

Or should we just put this in the docs?

**Comment by pavelzw** [comment] 2023-08-14 08:06
Maybe as an explicit feature flag in `pixi.toml`?

**Comment by baszalmstra** [comment] 2023-08-14 08:58
I'm not really a fan of that because I think it's user-specific, not project-specific.

**Comment by elliotwaite** [comment] 2023-10-20 12:23
What about making it a feature flag in an optional global config file? For example, it could be searched for at `~/.pixi/config.toml` (or a different path depending on the OS).

**Comment by jhoelzl** [comment] 2023-11-22 19:34
I added the file `.pixi/conda`, run `chmod +x conda` and then added a new conda environment with that path to Pycharm 2023.2.5 on MacOS. However, i get this error:

> The error is: "NotImplemented: ['create', 'y', 'n', 'my-env-name', 'python=3.11' raise NotImplementedError(str(sys.argv[1:]))

**Comment by jonashaag** [comment] 2023-11-22 19:47
The code snippet needs updating. I have a new version for Micromamba in my repo.

**Comment by yonil7** [comment] 2023-12-16 05:48
* For start, it will be good if we can have "pycharm integration" (and maybe also "vscode integration") section on the documentation that will guide people on how to use `pixi` with `pycharm`/`vscode`.
* Later, we can aim for making this integration as simple as possible. (one option would be to ask pycharm team to add formal support for `pixi` as they currently support conda, poetry, pipenv, virtualenv)

**Comment by pavelzw** [comment] 2024-03-12 00:39
I fixed the broken script. You can find it here: https://github.com/pavelzw/pixi-pycharm
It supports multi-envs, listing envs, listing packages and running stuff.

As of now, I haven't implemented "creating envs" and "installing dependencies" from pycharm yet. But at that point we might want to think about a proper extension instead.

**Comment by pavelzw** [comment] 2024-03-13 12:31
@jonashaag took a look at how feasible it is to create a pycharm plugin for pixi. 
It seems like pycharm's plugin api doesn't support custom package managers and you would need to add it to pycharm directly.
Not sure if JetBrains would like this change as then they would theoretically also need to accept PRs for rye, hatch, ... as well.

The only available configurations are the following:

![image](https://github.com/prefix-dev/pixi/assets/29506042/0825c765-a58e-4705-8ee3-16e0b9fbf801)

https://github.com/JetBrains/intellij-community/blob/467ba55677a0c5da1de1b1fc14ac699309ec5bb6/python/src/com/jetbrains/python/sdk/add/target/PyAddTargetBasedSdkDialog.kt#L29
https://github.com/JetBrains/intellij-community/blob/master/python/src/com/jetbrains/python/sdk/add/target/PyAddTargetBasedSdkPanel.kt#L100

I created a package that allows pycharm integrations with some hacks. It's not perfect but probably the best we can get without modifying intellij code directly.
It might make sense to talk to maintainers of pycharm and ask if they would be open to us adding pixi support directly in intellij or not.

But for now, I think #974 is enough to close this issue.

**Closed** 2024-03-14 07:29 UTC

**Comment by delsner** [comment] 2024-10-21 08:12
FTR: There's also an [open issue](https://youtrack.jetbrains.com/issue/PY-61600/Regression-in-support-for-the-pyAddSdkProv%5B%E2%80%A6%5D-extension-point-starting-with-Pycharm-CE-version-2022.2x) for the broken `pyAddSdkProvider` extension point, which is necessary to include a new python interpreter in the pycharm UI.
