### ISSUE TITLE
Fail to find packages when project in paths containing Unicode characters

### ISSUE THREAD

**Issue by yanecc** [prefix-dev/pixi#1189] opened 2024-04-14 07:16 UTC
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
pixi init jupyter
cd jupyter
pixi add jupyter
pixi run jupyter notebook
```

### Issue description

```
no module named 'XXXX'
```

### Expected behavior

It should work properly.

### Version

v0.19.1

**Comment by baszalmstra** [comment] 2024-04-14 09:27
Would you be able to elaborate a little bit on what you encounter and what you expect to work? 

I have tried this locally (on windows) and it seems to work on my machine. I can create a notebook and import modules added with `pixi add`.

**Comment by yanecc** [comment] 2024-04-14 09:38
> Would you be able to elaborate a little bit on what you encounter and what you expect to work?
> 
> I have tried this locally (on windows) and it seems to work on my machine. I can create a notebook and import modules added with `pixi add`.

I tried again and found that the issue occurs when the project path contains Unicode-encoded characters.

**Comment by yanecc** [comment] 2024-04-15 12:32
> Does jupyter fail or pixi? Could you give a complete step plan to reproduce? Including the path modification that breaks it?

pixi couldn't find any modules when there are Unicode characters in the project path.
```
B:/Temp/测试> pixi init
B:/Temp/测试> pixi add python
Added python
B:/Temp/测试> pixi add matplotlib
Added matplotlib
B:/Temp/测试> pixi run python test.py
Traceback (most recent call last):
  File "B:\Temp\测试\tree.py", line 1, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
```

**Comment by wolfv** [comment] 2024-04-15 13:26
I wonder if this is a Python problem ... or a problem of the `conda-forge` Python build. I am not sure this is a pixi-specific issue, unfortunately.

However, are you using `powershell` or `cmd.exe`?

**Comment by yanecc** [comment] 2024-04-15 15:14
> I wonder if this is a Python problem ... or a problem of the `conda-forge` Python build. I am not sure this is a pixi-specific issue, unfortunately.
> 
> However, are you using `powershell` or `cmd.exe`?

I'm using nushell, but the issue could reproduce whichever the shell is.

**Comment by yanecc** [comment] 2024-04-15 15:24
> Does jupyter fail or pixi? Could you give a complete step plan to reproduce? Including the path modification that breaks it?

This may be more clear. I have Python 3.9.9 installed in the Path.

```
B:\Temp\测试>pixi init
Initialized project in B:\Temp\测试\.

B:\Temp\测试>pixi add python
Added python                                                                                                                                                    B:\Temp\测试>pixi run python --version
Python 3.9.9

B:\Temp\测试>cd ../test

B:\Temp\test>pixi init
Initialized project in B:\Temp\test\.

B:\Temp\test>pixi add python
Added python                                                                                                                                                    B:\Temp\test>pixi run python --version
Python 3.12.2
```

**Comment by wolfv** [comment] 2024-04-16 09:37
Maybe we need to set the `chcp 65001` thing in the activation script so that unicode stuff works better. I can take a look.

**Comment by wolfv** [comment] 2024-04-16 12:35
Ok, I am just noting down some problems that I came across while debugging that (as a mental note).

When installing `git` globally with pixi, it adds a `env.bat` (or `env`) executable. This is somehow invoked when running the activation and breaks the execution of the activation script for some reason I haven't fully understood. I am removing git for now and first debugging the `run` (and `shell`?) issues.

**Comment by wolfv** [comment] 2024-04-16 13:05
So the problem is already with extracting the environment variables.
For some reason, the output appears garbled and we do not detect the start - and end markers properly.

The script looks something like this:

```bat
@chcp 65001
@SET
@ECHO ^<=== RATTLER ENV START ===^>
@SET "PATH=C:\Users\wolfv\Programs\uni\测\.pixi\envs\default;C:\Users\wolfv\Programs\uni\测\.pixi\envs\default\Library/mingw-w64/bin;C:\Users\wolfv\Programs\uni\测\.pixi\envs\default\Library/usr/bin;C:\Users\wolfv\Programs\uni\测\.pixi\envs\default\Library/bin;C:\Users\wolfv\Programs\uni\测\.pixi\envs\default\Scripts;C:\Users\wolfv\Programs\uni\测\.pixi\envs\default\bin;%PATH%"
@SET "CONDA_PREFIX=C:\Users\wolfv\Programs\uni\测\.pixi\envs\default"
@SET "PIXI_PROJECT_ROOT=C:\Users\wolfv\Programs\uni\测"
@SET "PIXI_ENVIRONMENT_PLATFORMS=win-64"
@SET "PIXI_PROMPT=(测) "
@SET "PIXI_PROJECT_NAME=测"
@SET "PIXI_PROJECT_VERSION=0.1.0"
@SET "PIXI_EXE=C:\Users\wolfv\Programs\pixi\target\debug\pixi.exe"
@SET "PIXI_IN_SHELL=1"
@SET "PIXI_ENVIRONMENT_NAME=default"
@SET "CONDA_DEFAULT_ENV=测"
@SET "PIXI_PROJECT_MANIFEST=C:\Users\wolfv\Programs\uni\测\pixi.toml"
@ECHO ^<=== RATTLER ENV START ===^>
@SET
```

But for some reason, the `@ECHO ^<=== RATTLER ENV START ===^>` seems to print the path or something like that. I need to investigate some more but hopefully we can write some tests in rattler.

**Comment by wolfv** [comment] 2024-04-16 20:40
I think this is the solution: https://github.com/mamba-org/rattler/pull/604 - at least it works locally. We'll try to get it in with the next release! Thanks for filing this bug.

**Comment by wolfv** [comment] 2024-04-21 08:00
@yanecc could you try with the latest pixi release? This issues should be fixed. Thanks again for the report!

**Closed by wolfv** 2024-04-21 08:00 UTC
Labels: bug, needs-more
