### ISSUE TITLE
Add version range to pypi-dependencies when using `pixi add --pypi` 

### ISSUE THREAD

**Issue by FunkMonkey** [prefix-dev/pixi#1409] opened 2024-05-18 16:28 UTC
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
pixi add EduData --pypi
```

### Issue description

Maybe I just have the wrong expectations, but when I added a package via the `--pypi` flag, the package was simply added like this to `pyproject.toml`:
`dependencies = ["edudata"]`

Is this the expected behaviour or should the package be added with default version ranges as discussed in #639? 

Thank you

### Expected behavior

Expected dependencies:
`dependencies = ["edudata >=0.0.18,<0.1"]`

**Comment by olivier-lacroix** [comment] 2024-05-19 02:19
It would make sense to be consistent between pypi and conda packages. Maybe not a bug but a enhancement?

**Comment by baszalmstra** [comment] 2024-07-19 04:38
@ruben-arts I though this was already implemented with the latest release?

**Comment by ruben-arts** [comment] 2024-07-19 05:32
I thought so too but want to make sure before closing the issue.

**Comment by ruben-arts** [comment] 2024-07-19 06:06
This is was actually fixed already in https://github.com/prefix-dev/pixi/pull/1508. 

Closing this as fixed. 

@SeanPedersen Are you trying with the latest release? If so and it still doesn't work, can you open a new issue with the non working `pixi.toml`/`pyproject.toml`?

**Closed by ruben-arts** 2024-07-19 06:06 UTC
Labels: enhancement, pypi
