### ISSUE TITLE
Pixi self-update missing `tag_name`

### ISSUE THREAD

**Issue by amirhosseindavoody** [prefix-dev/pixi#816] opened 2024-02-16 18:13 UTC
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
pixi self-update --force
```

### Issue description

I have pixi installed in a non default location using a symbolic link
`/path/to/home/directory/.pixi -> /path/to/home/directory/workspace/.pixi_for_home`

When I use the `pixi self-update --force`, I get the following error
```
× Failed to fetch latest version from github: missing field `tag_name` at line 1 column 277
```

### Expected behavior

Be able to update pixi on a non-default location.

**Comment by ruben-arts** [comment] 2024-02-17 08:41
Thanks for the info. I can't reproduce it yet. Will have to investigate some more.

**Comment by wolfv** [comment] 2024-02-17 09:19
It actually looks like a wrong JSON response from Github. I also tried yesterday and couldn't reproduce. Maybe we should print the returned JSON when we can't parse it?

**Comment by ruben-arts** [comment] 2024-02-22 09:33
The issue you had is not fixed but atleast with the next release you should get more information on what the actual error is. So I'm closing this for now.

**Closed by ruben-arts** 2024-02-22 09:33 UTC
Labels: bug
