### ISSUE TITLE
tkinter breaks in certain pixi paths.

### ISSUE THREAD

**Issue by richardsheridan** [prefix-dev/pixi#1096] opened 2024-04-01 21:20 UTC
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```powershell
mkdir test && cd test
pixi init && pixi add python && pixi run python -m tkinter
mkdir test1 && cd test1
pixi init && pixi add python && pixi run python -m tkinter
```

### Issue description

Just getting started today with pixi and I'm having a bizarre bug on Windows. If I use an even length path name, tkinter doesn't work. (actually could be odd, I'm not sure where to start counting). All other conda, micromamba, venv, etc. environments I have ever tried on this machine work fine, as well as pixi on wsl.  Let me know if there's a further test you'd like to see from my machine specifically.

Here's the output of testing specifically path lengths (no output is a success):
```text
(base) PS C:\Users\richard\Documents\GitHub> mkdir a

    Directory: C:\Users\richard\Documents\GitHub

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----          2024-04-01  5:02 PM                a

(base) PS C:\Users\richard\Documents\GitHub> cd a
(base) PS C:\Users\richard\Documents\GitHub\a> pixi init
✔ Initialized project in C:\Users\richard\Documents\GitHub\a\.
(base) PS C:\Users\richard\Documents\GitHub\a> pixi add python
✔ Added python
(base) PS C:\Users\richard\Documents\GitHub\a> pixi run python -m tkinter
(base) PS C:\Users\richard\Documents\GitHub\a> cd ..
(base) PS C:\Users\richard\Documents\GitHub> mkdir aa

    Directory: C:\Users\richard\Documents\GitHub

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----          2024-04-01  5:03 PM                aa

(base) PS C:\Users\richard\Documents\GitHub> cd aa
(base) PS C:\Users\richard\Documents\GitHub\aa> pixi init
✔ Initialized project in C:\Users\richard\Documents\GitHub\aa\.
(base) PS C:\Users\richard\Documents\GitHub\aa> pixi add python
✔ Added python
(base) PS C:\Users\richard\Documents\GitHub\aa> pixi run python -m tkinter
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\richard\Documents\GitHub\aa\.pixi\envs\default\Lib\tkinter\__main__.py", line 7, in <module>
    main()
  File "C:\Users\richard\Documents\GitHub\aa\.pixi\envs\default\Lib\tkinter\__init__.py", line 4639, in _test
    root = Tk()
           ^^^^
  File "C:\Users\richard\Documents\GitHub\aa\.pixi\envs\default\Lib\tkinter\__init__.py", line 2345, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_tkinter.TclError: Can't find a usable init.tcl in the following directories:
    {C:/Users/richard/Documents/GitHub/aa/.pixi/envs/default\Lib}



This probably means that Tcl wasn't installed properly.

(base) PS C:\Users\richard\Documents\GitHub\aa> cd ..
(base) PS C:\Users\richard\Documents\GitHub> mkdir aaa

    Directory: C:\Users\richard\Documents\GitHub

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----          2024-04-01  5:04 PM                aaa

(base) PS C:\Users\richard\Documents\GitHub> cd aaa
(base) PS C:\Users\richard\Documents\GitHub\aaa> pixi init
✔ Initialized project in C:\Users\richard\Documents\GitHub\aaa\.
(base) PS C:\Users\richard\Documents\GitHub\aaa> pixi add python
✔ Added python
(base) PS C:\Users\richard\Documents\GitHub\aaa> pixi run python -m tkinter
(base) PS C:\Users\richard\Documents\GitHub\aaa> cd ..
(base) PS C:\Users\richard\Documents\GitHub> cd aaaa
Set-Location: Cannot find path 'C:\Users\richard\Documents\GitHub\aaaa' because it does not exist.
(base) PS C:\Users\richard\Documents\GitHub> mkdir aaaa

    Directory: C:\Users\richard\Documents\GitHub

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----          2024-04-01  5:04 PM                aaaa

(base) PS C:\Users\richard\Documents\GitHub> cd aaaa
(base) PS C:\Users\richard\Documents\GitHub\aaaa> pixi init && pixi add python && pixi run python -m tkinter
✔ Initialized project in C:\Users\richard\Documents\GitHub\aaaa\.
✔ Added python
(base) PS C:\Users\richard\Documents\GitHub\aaaa> cd ..
(base) PS C:\Users\richard\Documents\GitHub> mkdir aaaaa && cd aaaaa

    Directory: C:\Users\richard\Documents\GitHub

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----          2024-04-01  5:05 PM                aaaaa

(base) PS C:\Users\richard\Documents\GitHub\aaaaa> pixi init && pixi add python && pixi run python -m tkinter
✔ Initialized project in C:\Users\richard\Documents\GitHub\aaaaa\.
✔ Added python
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\richard\Documents\GitHub\aaaaa\.pixi\envs\default\Lib\tkinter\__main__.py", line 7, in <module>
    main()
  File "C:\Users\richard\Documents\GitHub\aaaaa\.pixi\envs\default\Lib\tkinter\__init__.py", line 4639, in _test
    root = Tk()
           ^^^^
  File "C:\Users\richard\Documents\GitHub\aaaaa\.pixi\envs\default\Lib\tkinter\__init__.py", line 2345, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_tkinter.TclError: Can't find a usable init.tcl in the following directories:
    C:/Users/richard/Documents/GitHub/aaaaa/.pixi/envs/default\\



This probably means that Tcl wasn't installed properly.

(base) PS C:\Users\richard\Documents\GitHub\aaaaa> cd ..
(base) PS C:\Users\richard\Documents\GitHub> mkdir aaaaaa && cd aaaaaa

    Directory: C:\Users\richard\Documents\GitHub

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----          2024-04-01  5:06 PM                aaaaaa

(base) PS C:\Users\richard\Documents\GitHub\aaaaaa> pixi init && pixi add python && pixi run python -m tkinter
✔ Initialized project in C:\Users\richard\Documents\GitHub\aaaaaa\.
✔ Added python
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\richard\Documents\GitHub\aaaaaa\.pixi\envs\default\Lib\tkinter\__main__.py", line 7, in <module>
    main()
  File "C:\Users\richard\Documents\GitHub\aaaaaa\.pixi\envs\default\Lib\tkinter\__init__.py", line 4639, in _test
    root = Tk()
           ^^^^
  File "C:\Users\richard\Documents\GitHub\aaaaaa\.pixi\envs\default\Lib\tkinter\__init__.py", line 2345, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_tkinter.TclError: Can't find a usable init.tcl in the following directories:
    C:/Users/richard/Documents/GitHub/aaaaaa/.pixi/envs/default



This probably means that Tcl wasn't installed properly.

(base) PS C:\Users\richard\Documents\GitHub\aaaaaa>
```

### Expected behavior

tkinter should run!

**Comment by wolfv** [comment] 2024-04-01 21:35
Thanks! We'll look into this tomorrow.

**Comment by wolfv** [comment] 2024-04-02 06:34
Interesting, it seems to be the exact number of characters that triggers the bug - I am trying to dig a bit deeper to understand whats going on.

**Comment by wolfv** [comment] 2024-04-02 10:46
I was able to reproduce, and the referenced PR in rattler does indeed fix this issue on Windows. Thanks for filig the issue!

**Comment by ruben-arts** [comment] 2024-04-10 08:44
@wolfv This was fixed in the latest rattler update right?

**Comment by wolfv** [comment] 2024-04-10 09:59
yep!

**Closed** 2024-04-10 10:05 UTC
Labels: bug
