### ISSUE TITLE
Failed to install chumpy

### ISSUE THREAD

**Issue by chenzhekl** [prefix-dev/pixi#1891] opened 2024-08-23 06:17 UTC
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

Run the following command
```shell
pixi shell
```
with the following `pixi.toml`
```toml
[dependencies]
python = "~=3.10.0"
pip = "~=24.0.0"

[pypi-dependencies]
chumpy = { git = "https://github.com/mattloper/chumpy" }
```

### Issue description

This is the error I got:

```bash
  × failed to solve the pypi requirements of 'default' 'linux-64'
  ├─▶ failed to resolve pypi dependencies
  ├─▶ Failed to download and build `chumpy @ git+https://github.com/mattloper/chumpy`
  ├─▶ Failed to build: `chumpy @ git+https://github.com/mattloper/chumpy`
  ╰─▶ Build backend failed to determine extra requires with `build_wheel()` with exit status: 1
      --- stdout:

      --- stderr:
      Traceback (most recent call last):
        File "<string>", line 9, in <module>
      ModuleNotFoundError: No module named 'pip'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "<string>", line 14, in <module>
        File "/home/a/.cache/rattler/cache/uv-cache/environments-v0/.tmpKLzw0Y/lib/python3.10/site-packages/setuptools/
      build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "/home/a/.cache/rattler/cache/uv-cache/environments-v0/.tmpKLzw0Y/lib/python3.10/site-packages/setuptools/
      build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "/home/a/.cache/rattler/cache/uv-cache/environments-v0/.tmpKLzw0Y/lib/python3.10/site-packages/setuptools/
      build_meta.py", line 502, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/home/a/.cache/rattler/cache/uv-cache/environments-v0/.tmpKLzw0Y/lib/python3.10/site-packages/setuptools/
      build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 11, in <module>
      ModuleNotFoundError: No module named 'pip'
```

### Expected behavior

I expect it to work just like with `pip`

**Comment by ruben-arts** [comment] 2024-08-23 08:37
This issue is a duplicate of https://github.com/prefix-dev/pixi/issues/1880. We're working on a fix!

**Closed by ruben-arts** 2024-08-23 08:37 UTC
Labels: bug

**Comment by tdejager** [comment] 2024-09-03 12:06
Try using the build-isolation options in the next release: https://pixi.sh/dev/reference/project_configuration/#no-build-isolation

**Comment by AClon314** [comment] 2025-06-09 02:36
chumpy now can be installed with this `pyproject.toml`:

```toml
[tool.pixi.environments]
default = {features = ["CHUMPY"]}
[tool.pixi.feature.CHUMPY.dependencies]
pip = "*"  # 1. install conda dep
[tool.pixi.feature.CHUMPY.pypi-dependencies]
chumpy = {git = "https://github.com/mattloper/chumpy"}  # 2. install pypi dep
[tool.pixi.feature.CHUMPY.pypi-options]
no-build-isolation = ["chumpy"]  # chumpy could access conda dep/conda env
```
